#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2023.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Aug 12 20:47:18 PDT 2025
# SW Build 4029153 on Fri Oct 13 20:13:54 MDT 2023
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim test_behav -key {Behavioral:sim_1:Functional:test} -tclbatch test.tcl -wdb /localhdd/arb26/workspace/brahmalocal/brahma/apps/bandwidth_poco/vivado/tapa-fast-cosim.sim/sim_1/behav/xsim/wave.wdb -log simulate.log"
xsim test_behav -key {Behavioral:sim_1:Functional:test} -tclbatch test.tcl -wdb /localhdd/arb26/workspace/brahmalocal/brahma/apps/bandwidth_poco/vivado/tapa-fast-cosim.sim/sim_1/behav/xsim/wave.wdb -log simulate.log

